const Canada = [
  {
    slug: "AB",
    name: "Alberta",
    cities: [
      "Calgary",
      "Edmonton",
      "Red Deer",
      "Lethbridge",
      "Medicine Hat",
      "Grande Prairie",
      "Fort McMurray",
      "Camrose",
      "Brooks",
      "Wetaskiwin",
      "Hinton",
      "Banff",
      "Vegreville",
      "Stettler",
      "Peace River",
      "Jasper",
      "Fort Chipewyan",
      "Lac La Biche",
      "Athabasca",
      "Lake Louise",
    ],
  },
  {
    slug: "BC",
    name: "British Columbia",
    cities: [
      "Vancouver",
      "Victoria",
      "Abbotsford",
      "Kelowna",
      "Nanaimo",
      "Kamloops",
      "Prince George",
      "Chilliwack",
      "Penticton",
      "Campbell River",
      "Courtenay",
      "Terrace",
      "Fort Saint John",
      "Cranbrook",
      "Prince Rupert",
      "Williams Lake",
      "Quesnel",
      "Powell River",
      "Nelson",
      "Dawson Creek",
      "Revelstoke",
      "Fort Nelson",
      "Smithers",
      "Creston",
      "Lillooet",
      "Burns Lake",
      "Port Hardy",
      "Tofino",
      "New Bella Bella",
      "Sandspit",
      "Dease Lake",
    ],
  },
  {
    slug: "MB",
    name: "Manitoba",
    cities: [
      "Winnipeg",
      "Brandon",
      "Thompson",
      "Selkirk",
      "Steinbach",
      "Dauphin",
      "Flin Flon",
      "The Pas",
      "Norway House",
      "Gimli",
      "Nelson House",
      "Gillam",
      "Churchill",
      "Berens River",
      "Shamattawa",
      "Lynn Lake",
      "Pukatawagan",
      "Brochet",
      "Oxford House",
      "Island Lake",
    ],
  },
  {
    slug: "NB",
    name: "New Brunswick",
    cities: ["Moncton", "Saint John", "Fredericton", "Edmundston", "Bathurst"],
  },
  {
    slug: "NL",
    name: "Newfoundland and Labrador",
    cities: [
      "Saint John’s",
      "Corner Brook",
      "Happy Valley",
      "Stephenville",
      "Channel-Port aux Basques",
      "Deer Lake",
      "Gander",
      "Nain",
      "Argentia",
      "La Scie",
      "Buchans",
      "Cartwright",
      "Trout River",
      "Forteau Bay",
      "Hopedale",
      "Trepassey",
      "Saint Anthony",
      "Port Hope Simpson",
      "Rigolet",
    ],
  },
  {
    slug: "NS",
    name: "Nova Scotia",
    cities: [
      "Halifax",
      "Sydney",
      "New Glasgow",
      "Amherst",
      "Yarmouth",
      "Antigonish",
      "Liverpool",
      "Digby",
      "Windsor",
      "Shelburne",
      "Baddeck",
    ],
  },
  {
    slug: "NT",
    name: "Northwest Territories",
    cities: [
      "Yellowknife",
      "Hay River",
      "Inuvik",
      "Fort McPherson",
      "Norman Wells",
      "Tuktoyaktuk",
      "Fort Good Hope",
      "Délįne",
      "Fort Smith",
      "Holman",
      "Fort Resolution",
      "Paulatuk",
      "Fort Simpson",
      "Tsiigehtchic",
      "Łutselk’e",
    ],
  },
  {
    slug: "NU",
    name: "Nunavut",
    cities: [
      "Iqaluit",
      "Rankin Inlet",
      "Arviat",
      "Igloolik",
      "Baker Lake",
      "Pond Inlet",
      "Cambridge Bay",
      "Cape Dorset",
      "Pangnirtung",
      "Kugluktuk",
      "Gjoa Haven",
      "Repulse Bay",
      "Coral Harbour",
      "Taloyoak",
      "Hall Beach",
      "Arctic Bay",
      "Kimmirut",
      "Chesterfield Inlet",
      "Resolute",
      "Alert",
      "Grise Fiord",
      "Ennadai",
    ],
  },
  {
    slug: "ON",
    name: "Ontario",
    cities: [
      "Toronto",
      "Ottawa",
      "Hamilton",
      "Oshawa",
      "Kitchener",
      "London",
      "Windsor",
      "Barrie",
      "Sudbury",
      "Sarnia",
      "Kingston",
      "Thunder Bay",
      "Peterborough",
      "North Bay",
      "Cornwall",
      "Belleville",
      "Orillia",
      "Timmins",
      "Orangeville",
      "Brockville",
      "Owen Sound",
      "Pembroke",
      "Kenora",
      "Kapuskasing",
      "Dryden",
      "Parry Sound",
      "New Liskeard",
      "Hearst",
      "Marathon",
      "Cochrane",
      "Deer Lake",
      "Atikokan",
      "Chapleau",
      "Wiarton",
      "Wawa",
      "Attawapiskat",
      "Red Lake",
      "Moosonee",
      "Little Current",
      "Thessalon",
      "Cobalt",
      "Geraldton",
      "Nipigon",
      "Cat Lake",
      "Fort Severn",
      "Lansdowne House",
      "Big Beaverhouse",
    ],
  },
  {
    slug: "PE",
    name: "Prince Edward Island",
    cities: ["Charlottetown"],
  },
  {
    slug: "QC",
    name: "Quebec",
    cities: [
      "Montréal",
      "Québec",
      "Sherbrooke",
      "Trois-Rivières",
      "Saint-Jérôme",
      "Drummondville",
      "Chicoutimi",
      "Shawinigan-Sud",
      "Joliette",
      "Victoriaville",
      "Rimouski",
      "Saint-Georges",
      "Sept-Îles",
      "Rouyn-Noranda",
      "Val-d’Or",
      "Rivière-du-Loup",
      "Dolbeau",
      "Mont-Laurier",
      "Amos",
      "Baie-Comeau",
      "La Sarre",
      "Saint-Augustin",
      "Gaspé",
      "Matagami",
      "Inukjuak",
      "Cap-Chat",
      "Kuujjuaq",
      "Natashquan",
      "Mingan",
      "Kangirsuk",
      "Schefferville",
      "Eastmain",
      "Radisson",
      "Port-Menier",
      "Ivujivik",
      "Salluit",
    ],
  },
  {
    slug: "SK",
    name: "Saskatchewan",
    cities: [
      "Saskatoon",
      "Regina",
      "Prince Albert",
      "Moose Jaw",
      "North Battleford",
      "Yorkton",
      "Swift Current",
      "Weyburn",
      "Meadow Lake",
      "Kindersley",
      "Melville",
      "La Ronge",
      "Biggar",
      "Hudson Bay",
      "Stony Rapids",
      "Uranium City",
    ],
  },
  {
    slug: "YT",
    name: "Yukon",
    cities: ["Whitehorse", "West Dawson", "Watson Lake", "Burwash Landing"],
  },
];

export default Canada;